### PR TITLE
Xss mods

### PR DESCRIPTION
**Pull request by shivababuh**

### CODE REVIEW

**Review by aronsky — CHANGES_REQUESTED** [review]
Looks good overall, but there's a lot of repeated code. I would create an intermediate class that extends `HttpServlet` and provides implementations for `doGet`, `goodSanitationForTag`, and `goodSanitationForIdAttribute` (while we're at it, the last 2 should probably be called `sanitizeTag` and `sanitizeAttribute`).

Then, all the new `BenchmarkTest` classes can extend the above intermediate class, and only override the `doPost` method.

**Comment by lakshmankaveti1911** [comment]
> _No description provided._



> Looks good overall, but there's a lot of repeated code. I would create an intermediate class that extends `HttpServlet` and provides implementations for `doGet`, `goodSanitationForTag`, and `goodSanitationForIdAttribute` (while we're at it, the last 2 should probably be called `sanitizeTag` and `sanitizeAttribute`).
> 
> Then, all the new `BenchmarkTest` classes can extend the above intermediate class, and only override the `doPost` method.



> Looks good overall, but there's a lot of repeated code. I would create an intermediate class that extends `HttpServlet` and provides implementations for `doGet`, `goodSanitationForTag`, and `goodSanitationForIdAttribute` (while we're at it, the last 2 should probably be called `sanitizeTag` and `sanitizeAttribute`).
> 
> Then, all the new `BenchmarkTest` classes can extend the above intermediate class, and only override the `doPost` method.



> Looks good overall, but there's a lot of repeated code. I would create an intermediate class that extends `HttpServlet` and provides implementations for `doGet`, `goodSanitationForTag`, and `goodSanitationForIdAttribute` (while we're at it, the last 2 should probably be called `sanitizeTag` and `sanitizeAttribute`).
> 
> Then, all the new `BenchmarkTest` classes can extend the above intermediate class, and only override the `doPost` method.

Hi Aronsky, basically in Benchmark structure for each test case there is a java file, an html file and an xml. If we need to create a intermediate class, we should optimize all these files. And also, the sanitization code is different for each scenario. Please suggest!

**Comment by lakshmankaveti1911** [comment]
Hi Aronsky, basically in Benchmark structure for each test case there is a java file, an html file and an xml. If we need to create a intermediate class, we should optimize all these files. And also, the sanitization code is different for each scenario. Please suggest

**Comment by aronsky** [comment]
Why would creating an intermediate class require any changes to the HTML/XML files? And I see that there are 2 kinds of `goodSanitationForTag` - those could be split into 2 different functions in the intermediate class.

**Comment by lakshmankaveti1911** [comment]
> Why would creating an intermediate class require any changes to the HTML/XML files? And I see that there are 2 kinds of `goodSanitationForTag` - those could be split into 2 different functions in the intermediate class.

Hi Aronsky, Java does not support multiple inheritance. So the Intermediate class cannot extends HttpServelt. Please suggest!

**Comment by aronsky** [comment]
No multiple inheritance required. Create an intermediate class that extends `HttpServlet`, and make all the new BenchmarkTest classes from this PR extend that class. That's not multiple inheritance, as each class in the hierarchy has a single immediate parent.

**Review by aronsky — CHANGES_REQUESTED** [review]
Great. However, `Intermediate` is not a good class name. Rename it to something like `SanitizingHttpServlet`.

And please remove the code that you commented out, which is no longer used.

**Review by aronsky — APPROVED** [review]
Great, looks good to me.

**Pull request merged**
